version: '3.8'
services:
  pgdb:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - /pgdata/scanwize:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DB}
    networks:
      - scanwize
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger-docs-scanwize
    expose:
      - 8080
    ports:
      - 7050:8080
    environment:
      SWAGGER_JSON: /docs.yaml
    volumes:
      - ./api/docs/api.yaml:/docs.yaml
    networks:
      - scanwize
  api:
    build: ./api
    container_name: auth_api
    restart:  always
    depends_on:
      - pgdb
    ports:
      - 3000:3000
    environment:
      - PG_USER=${PG_USER}
      - PG_PASSWORD=${PG_PASSWORD}
      - PG_DB=${PG_DB}
      - PG_HOST=${PG_HOST}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRY=${JWT_EXPIRY}
      - SALT_ROUNDS=${SALT_ROUNDS}
    networks:
      - scanwize
networks:
  scanwize:
    driver: bridge